return {
    _PlainText                          = { fg = "base7" },
    _Comments                           = { fg = "base5" },
    _Marks                              = { fg = "base6", bold = true },
    _Strings                            = { fg = "red" },
    _Characters                         = { fg = "yellow" },
    _Numbers                            = { fg = "yellow" },
    _Keywords                           = { fg = "pink", bold = true },
    _PreprocessorStatements             = { fg = "orange" },
    _URL                                = { fg = "strong_blue1", underline = true },
    _Attributes                         = { fg = "light_brown" },
    -- TypeDeclarations                   = { fg = "light_blue" },
    _OtherDeclarations                  = { fg = "blue" },
    -- ProjectClassnames                  = { fg = "teal" },
    -- ProjectFunctionAndMethodNames      = { fg = "light_teal" },
    -- ProjectConstants                   = { fg = "light_teal" },
    _ProjectTypeNames                   = { fg = "teal" },
    _ProjectInstanceVariablesAndGlobals = { fg = "teal" },
    -- ProjectPreprocessorMacros          = { fg = "brown" },
    -- OtherClassNames                    = { fg = "light_purple" },
    _OtherFunctionAndMethodNames        = { fg = "purple" },
    _OtherConstants                     = { fg = "purple" },
    _OtherTypeNames                     = { fg = "light_purple" },
    -- OtherInstanceVariablesAndGlobals   = { fg = "purple" },
    -- OtherPreprocessorMacros            = { fg = "orange" },

    -- Markup
    Normal                              = { fg = "base7", bg = "base0" },
    None                                = {},
    Underlined                          = { fg = "light_blue", underline = true },
    Bold                                = { fg = "base7", bold = true },
    Italic                              = { fg = "base7", italic = true },
    Strikethrough                       = { fg = "base7", strikethrough = true },
    _Spell                              = { undercurl = true },

    -- UI
    Error                               = { fg = "base0", bg = "red" },
    Directory                           = { fg = "light_blue" },
    LineNr                              = { fg = "base4" },
    Pmenu                               = { fg = "base7", bg = "base2" },
    PmenuSbar                           = { fg = "base2", bg = "base2" },
    PmenuSel                            = { fg = "base7", bg = "deep_blue0" },
    PmenuThumb                          = { fg = "base3", bg = "base3" },
    Search                              = { fg = "base7", bg = "base3" },
    IncSearch                           = { fg = "base0", bg = "deep_yellow" },
    Visual                              = { bg = "base3" },
    CursorLine                          = { bg = "base1" },
    ErrorMsg                            = { fg = "red" },
    ModeMsg                             = { fg = "base5" },
    MoreMsg                             = { fg = "pink" },
    Question                            = { fg = "pink" },
    WarningMsg                          = { fg = "orange" },
    Special                             = { fg = "teal" },
    Ignore                              = { fg = "base3" },
    DiffAdd                             = { bg = "green_wash" },
    DiffChange                          = { bg = "orange_wash" },
    DiffDelete                          = { bg = "red_wash" },
    DiffText                            = {},
    QuickFixLine                        = { fg = "base7", bg = "deep_blue0" },
    StatusLine                          = { fg = "base7", bg = "base3" },
    StatusLineNC                        = { fg = "base6", bg = "base3" },
    TabLine                             = { fg = "base7", bg = "base3" },
    TabLineSel                          = { fg = "base5", bg = "base2" },
    VertSplit                           = { fg = "base3", bg = "base3" },
    WinSeparator                        = { fg = "base3" },
    WildMenu                            = { fg = "base7" },
    FloatNormal                         = { fg = "base7", bg = "base2" },
    FloatBorder                         = { fg = "base2", bg = "base2" },
    ColorColumn                         = { fg = "base3", bg = "base3" },
    FoldColumn                          = { fg = "base4" },
    Folded                              = { fg = "base4", bg = "base2" },

    -- Help pages
    _Heading                            = { fg = "pink" },
    _HyperTextJump                      = { fg = "light_teal", underline = true },
    _HyperTextEntry                     = { fg = "light_teal" },
    helpWarning                         = { fg = "orange", bold = true },
    helpDeprecated                      = { fg = "orange",  strikethrough = true },

    -- marks.nvim
    MarkSignHL                          = { fg = "base4" },

    manOptionDesc                       = { fg = "light_purple", bold = true }
}
