return {
    _PlainText                          = { fg = "base6" },
    _Comments                           = { fg = "base4" },
    _Marks                              = { fg = "base5", bold = true },
    _Strings                            = { fg = "red" },
    _Characters                         = { fg = "strong_blue0" },
    _Numbers                            = { fg = "strong_blue0" },
    _Keywords                           = { fg = "pink", bold = true },
    _PreprocessorStatements             = { fg = "brown" },
    _URL                                = { fg = "strong_blue1", underline = true },
    _Attributes                         = { fg = "light_brown" },
    -- TypeDeclarations                   = { fg = "dark_blue" },
    _OtherDeclarations                  = { fg = "blue" },
    -- ProjectClassnames                  = { fg = "dark_teal" },
    -- ProjectFunctionAndMethodNames      = { fg = "teal" },
    -- ProjectConstants                   = { fg = "teal" },
    _ProjectTypeNames                   = { fg = "dark_teal" },
    _ProjectInstanceVariablesAndGlobals = { fg = "teal" },
    -- ProjectPreprocessorMacros          = { fg = "brown" },
    -- OtherClassNames                    = { fg = "dark_purple" },
    _OtherFunctionAndMethodNames        = { fg = "purple" },
    _OtherConstants                     = { fg = "purple" },
    _OtherTypeNames                     = { fg = "dark_purple" },
    -- OtherInstanceVariablesAndGlobals   = { fg = "purple" },
    -- OtherPreprocessorMacros            = { fg = "brown" },

    -- Markup
    Normal                             = { fg = "base6", bg = "base0" },
    None                               = {},
    Underlined                         = { fg = "blue", underline = true },
    Bold                               = { fg = "base6", bold = true },
    Italic                             = { fg = "base6", italic = true },
    Strikethrough                      = { fg = "base6", strikethrough = true },
    _Spell                              = { undercurl = true },

    -- UI
    Error                              = { fg = "base0", bg = "red" },
    Directory                          = { fg = "blue" },
    LineNr                             = { fg = "base3" },
    Pmenu                              = { fg = "base6", bg = "base1" },
    PmenuSbar                          = { fg = "base1", bg = "base1" },
    PmenuSel                           = { fg = "base0", bg = "deep_blue0" },
    PmenuThumb                         = { fg = "base2", bg = "base2" },
    Search                             = { fg = "base6", bg = "base2" },
    IncSearch                          = { fg = "base6", bg = "deep_yellow" },
    Visual                             = { bg = "aqua" },
    CursorLine                         = { bg = "light_aqua" },
    ErrorMsg                           = { fg = "red" },
    ModeMsg                            = { fg = "base4" },
    MoreMsg                            = { fg = "pink" },
    Question                           = { fg = "pink" },
    WarningMsg                         = { fg = "brown" },
    Special                            = { fg = "dark_teal" },
    Ignore                             = { fg = "base3" },
    DiffAdd                            = { bg = "green_wash" },
    DiffChange                         = { bg = "yellow_wash" },
    DiffDelete                         = { bg = "red_wash" },
    DiffText                           = {},
    QuickFixLine                       = { fg = "base0", bg = "deep_blue0" },
    StatusLine                         = { fg = "base5", bg = "base3" },
    StatusLineNC                       = { fg = "base6", bg = "base3" },
    TabLine                            = { fg = "base6", bg = "base1" },
    TabLineSel                         = { fg = "base6", bg = "base2" },
    VertSplit                          = { fg = "base3", bg = "base3" },
    WinSeparator                       = { fg = "base3" },
    WildMenu                           = { fg = "base0" },
    FloatNormal                        = { fg = "base6", bg = "base2" },
    FloatBorder                        = { fg = "base1", bg = "base1" },
    ColorColumn                        = { fg = "base3", bg = "base3" },
    FoldColumn                         = { fg = "base3" },
    Folded                             = { fg = "base4", bg = "base1" },

    -- Help pages
    _Heading                           = { fg = "pink" },
    _HyperTextJump                     = { fg = "teal", underline = true },
    _HyperTextEntry                    = { fg = "teal" },
    helpWarning                        = { fg = "brown", bold = true },
    helpDeprecated                     = { fg = "brown",  strikethrough = true },

    -- marks.nvim
    MarkSignHL                         = { fg = "base5" },

    -- man
    manOptionDesc                      = { fg = "purple", bold = true }
}
