return {
    -- Standard highlight groups
    String                  = "_Strings",
    Character               = "_Characters",
    Number                  = "_Numbers",
    Comment                 = "_Comments",
    Keyword                 = "_Keywords",
    PreProc                 = "_PreprocessorStatements",
    Parameter               = "_OtherDeclarations",
    Constant                = "_OtherConstants",
    Float                   = "_Numbers",
    StringDelimiter         = "_Strings",
    Identifier              = "_OtherConstants",
    Function                = "_OtherFunctionAndMethodNames",
    Statement               = "_Keywords",
    Boolean                 = "_Keywords",
    Conditional             = "_Keywords",
    Exception               = "_Keywords",
    Include                 = "_Keywords",
    Keywords                = "_Keywords",
    Label                   = "_Keywords",
    Repeat                  = "_Keywords",
    StorageClass            = "_Keywords",
    Structure               = "_Keywords",
    Define                  = "_PreprocessorStatements",
    Macro                   = "_PreprocessorStatements",
    PreCondit               = "_PreprocessorStatements",
    Type                    = "_OtherTypeNames",
    Todo                    = "_Marks",
    Typedef                 = "_Keywords",
    Delimiter               = "_PlainText",
    Operator                = "_PlainText",

    -- Markup
    Title                   = "_Marks",
    SpellBad                = "_Spell",
    SpellCap                = "_Spell",
    SpellLocal              = "_Spell",
    SpellRare               = "_Spell",

    -- UI
    SignColumn              = "LineNr",
    CursorColumn            = "CursorLine",
    CursorLineNr            = "CursorLine",
    TabLineFill             = "TabLine",
    MatchParen              = "IncSearch",
    MatchWord               = "IncSearch",
    Terminal                = "_PlainText",
    StatusLineTerm          = "StatusLine",
    StatusLineTermNC        = "StatusLineNC",
    VisualNOS               = "Visual",
    EndOfBuffer             = "LineNr",
    qfLineNr                = "_PlainText",
    MsgArea                 = "_PlainText",
    Debug                   = "Special",
    SpecialChar             = "Special",
    Tag                     = "Special",
    Noise                   = "_PlainText",
    Quote                   = "_PlainText",
    Conceal                 = "Ignore",
    NonText                 = "Ignore",
    SpecialKey              = "Ignore",
    Whitespace              = "Ignore",

    -- Diff
    diffAdded               = "DiffAdd",
    diffBDiffer             = "WarningMsg",
    diffChanged             = "DiffChange",
    diffCommon              = "WarningMsg",
    diffDiffer              = "WarningMsg",
    diffFile                = "Directory",
    diffIdentical           = "WarningMsg",
    diffIndexLine           = "_Numbers",
    diffIsA                 = "WarningMsg",
    diffNoEOL               = "WarningMsg",
    diffOnly                = "WarningMsg",
    diffRemoved             = "DiffDelete",

    -- Help
    helpHyperTextJump       = "_HyperTextJump",
    helpHyperTextEntry      = "_HyperTextEntry",
    -- helpHeadline            = "Title",
    helpHeadline            = "_Keywords",
    helpHeader              = "_OtherTypeNames",
    helpSectionDelim        = "_Comments",
    helpVim                 = "_Keywords",
    helpExample             = "_OtherFunctionAndMethodNames",
    helpCommand             = "_OtherFunctionAndMethodNames",
    helpOption              = "_OtherTypeNames",
    helpSpecial             = "_OtherDeclarations",
    helpNote                = "Title",
    helpURL                 = "_URL",

    manSubHeading           = "_OtherTypeNames",
    manReference            = "_HyperTextJump",
}
